[Project]
name = 'unnamed'
grid_model_path = 'C:\Users\jpeddy\storage-sim\test_circuit.dss'


[storage-options."NewBESS"]
phases = 3
required = true
min_soc = 0.2
max_soc = 0.8
initial_soc = 0.5
busses = ['loadbus2']
power = [500.0]
duration = [6.0]


[storage-options."NewBESS".control-params]
mode = 'droop'


[storage-options."NewBESS".control-params.droop]
"p_droop" = 500.0
"q_droop" = -300.0


[storage-options."NewBESS".control-params.voltvar]
"volts" = [0.5, 0.95, 1.0, 1.05, 1.5]
"vars" = [1.0, 1.0, 0.0, -1.0, -1.0]


[storage-options."NewBESS".control-params.voltwatt]
"volts" = [0.5, 0.95, 1.0, 1.05, 1.5]
"watts" = [1.0, 1.0, 0.0, -1.0, -1.0]


[storage-options."NewBESS".control-params.varwatt]
"vars" = [0.5, 0.95, 1.0, 1.05, 1.5]
"watts" = [1.0, 1.0, 0.0, -1.0, -1.0]


[storage-options."NewBESS".control-params.vv_vw]
"vv_volts" = [0.5, 0.95, 1.0]
"vv_vars" = [1.0, 1.0, 0.0]
"vw_volts" = [0.5, 0.95, 1.0]
"vw_watts" = [1.0, 1.0, 0.0]


[storage-options."NewBESS".control-params.constantpf]
"pf_val" = 0.99


[metrics."Bus Voltage"]
values=[{name="regbus", lower_limit = 0.9, upper_limit = 1.1, objective = 1.0, sense = "Minimize"},
{name="loadbus3", lower_limit = 0.9, upper_limit = 1.1, objective = 1.0, sense = "Minimize"},
{name="loadbus2", lower_limit = 0.9, upper_limit = 1.1, objective = 1.0, sense = "Minimize"},
{name="loadbus1", lower_limit = 0.9, upper_limit = 1.1, objective = 1.0, sense = "Minimize"},
{name="subbus", lower_limit = 0.9, upper_limit = 1.1, objective = 1.0, sense = "Minimize"},
{name="sourcebus", lower_limit = 0.9, upper_limit = 1.1, objective = 1.0, sense = "Minimize"},
]