[Project]
name = 'unnamed'
grid_model_path = 'C:\Users\jpeddy\storage-sim\examples\ieee13demo\IEEE13Nodeckt.dss'
[reliability]
[reliability.line]
enabled = false
[reliability.switch]
enabled = false
[reliability.generator]
enabled = false
aging = {enabled = false}
operating_wear_out = {enabled = false}

[storage-options."MyDevice"]
phases = 3
required = true
min_soc = 0.2
max_soc = 0.8
initial_soc = 0.5
busses = ['633','671','650','646','634','675','sourcebus']
power = [200.0, 100.0, 300.0]
duration = [1.0, 2.0, 3.0]


[storage-options."MyDevice".control-params]
mode = 'droop'


[storage-options."MyDevice".control-params.droop]
"p_droop" = 500.0
"q_droop" = -300.0


[storage-options."NewBESS"]
phases = 3
required = true
min_soc = 0.2
max_soc = 0.8
initial_soc = 0.5
busses = ['670','611']
power = [568.0, 874.0, 526.0]
duration = [1.0, 2.0]


[storage-options."NewBESS".control-params]
mode = 'droop'


[storage-options."NewBESS".control-params.droop]
"p_droop" = 500.0
"q_droop" = -300.0
