name: "Build & Deploy Documentation"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5 
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        pip install .
        pip install -U matplotlib
    - name: run command
      run: python -c "import matplotlib.pyplot as plt"
    - name: run command
      run: python -c "import matplotlib.pyplot as plt; from helics import HelicsFederate"
    - name: run command
      run: python -c "from helics import HelicsFederate; import matplotlib.pyplot as plt"
    - name: run reproduction script
      run: python reproduce_segfault.py
